---
- hosts: localhost
  connection: local
  remote_user: root
  vars:
    host_name: satori

  tasks:
    #    - name: "update hostname"
    #hostname:
    #name: "{{ host_name }}"
    - name: "use non filtered flathub repo"
      flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: flathub

  roles:
    - base
    - bitwarden
    - teams
    - zoom
    - brave
    - element
    - joplin
    - plexamp
    - vscode
