---
- hosts: localhost
  connection: local
  remote_user: root
  vars:
    host_name: satori
    expresvpn_version: 2

  tasks:
    #    - name: "update hostname"
    #hostname:
    #name: "{{ host_name }}"

  roles:
    - flathub
    - base
    - bitwarden
    - teams
    - zoom
    - brave
    - element
    - joplin
    - plexamp
    - vscode
