---
- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - include_vars: ../local_vars.yaml
    - name: "update hostname"
      hostname:
        name: "{{ host_name }}"

  roles:
    - flathub
    - base
    - bitwarden
    - teams
    - zoom
    - brave
    - element
    - joplin
    - plexamp
    - vscode
