---
- name: add microsoft yum key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: add vscode repo
  yum_repository:
    name: vscode
    description: vscode yum repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
- name: install vscode
  dnf:
    name: code
    state: latest
