---
- name: "check flathub remote"
  shell: flatpak remotes | grep flathub
  register: flathub_remote
- debug:
    var: flathub_remote
- name: "use non filtered flathub repo"
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub/flatpakrepo
  when: flathub_remote.stdout != "flathub\tsystem"
