---
- name: add brave key
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
- name: add brave repo
  yum_repository:
    name: brave
    description: brave yum repo
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
- name: install brave
  dnf:
    name: brave-browser
    state: latest
