---
- name: "installing basic packages"
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - bat 
    - fzf 
    - wl-clipboard 
    - exa 
    - fd-find 
    - procs
    - sd
    - ripgrep
    #    - nextcloud-client
